package model;
// Generated 25/09/2017 16:05:29 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Loja generated by hbm2java
 */
@Entity
@Table(name = "loja")
public class Loja implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id_loja;
    private String loja;

    public Loja() {
    }

    public Loja(String loja) {
        this.loja = loja;
    }

    public Integer getId_loja() {
        return id_loja;
    }

    public void setId_loja(Integer id_loja) {
        this.id_loja = id_loja;
    }

    public String getLoja() {
        return loja;
    }

    public void setLoja(String loja) {
        this.loja = loja;
    }

}
