package model;
// Generated 25/09/2017 16:05:29 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Montagem generated by hbm2java
 */
@Entity
@Table(name = "montagem")
public class Montagem implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id_montagem;
    private Integer id_usuario;
    private String data_montagem;

    public Montagem() {
    }

    public Integer getId_montagem() {
        return id_montagem;
    }

    public void setId_montagem(Integer id_montagem) {
        this.id_montagem = id_montagem;
    }

    public Integer getId_usuario() {
        return id_usuario;
    }

    public void setId_usuario(Integer id_usuario) {
        this.id_usuario = id_usuario;
    }

    public String getData_montagem() {
        return data_montagem;
    }

    public void setData_montagem(String data_montagem) {
        this.data_montagem = data_montagem;

    }

}
