package model;
// Generated 25/09/2017 16:05:29 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Peca_loja generated by hbm2java
 */
@Entity
@Table(name = "peca_loja")
public class Peca_loja implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id_peca_loja;
    private Integer id_peca;
    private Integer id_loja;

    public Peca_loja() {
    }

    public Integer getId_peca_loja() {
        return id_peca_loja;
    }

    public void setId_peca_loja(Integer id_peca_loja) {
        this.id_peca_loja = id_peca_loja;
    }

    public Integer getId_peca() {
        return id_peca;
    }

    public void setId_peca(Integer id_peca) {
        this.id_peca = id_peca;
    }

    public Integer getId_loja() {
        return id_loja;
    }

    public void setId_loja(Integer id_loja) {
        this.id_loja = id_loja;
    }

}
