package model;
// Generated 25/09/2017 16:05:29 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Loja generated by hbm2java
 */
@Entity
@Table(name = "peca_montagem")
public class Peca_montagem implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id_peca_montagem;
    private Integer id_peca;
    private Integer id_montagem;

    public Peca_montagem() {
    }

    public Integer getId_peca_montagem() {
        return id_peca_montagem;
    }

    public void setId_peca_montagem(Integer id_peca_montagem) {
        this.id_peca_montagem = id_peca_montagem;
    }

    public Integer getId_peca() {
        return id_peca;
    }

    public void setId_peca(Integer id_peca) {
        this.id_peca = id_peca;
    }

    public Integer getId_montagem() {
        return id_montagem;
    }

    public void setId_montagem(Integer id_montagem) {
        this.id_montagem = id_montagem;
    }

}
