package model;
// Generated 25/09/2017 16:05:29 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tipo_Peca generated by hbm2java
 */
@Entity
@Table(name = "tipo_peca")

public class Tipo_peca implements java.io.Serializable {

    private Integer id_tipo_peca;
    private String nome;
    private String descricao;

    public Tipo_peca() {
    }

    public Tipo_peca(String nome, String descricao) {
        this.nome = nome;
        this.descricao = descricao;

    }

    @Id
    @GeneratedValue

    @Column(name = "id_tipo_peca", nullable = false)
    public Integer getIdTipo_Peca() {
        return this.id_tipo_peca;
    }

    public void setIdTipo_Peca(Integer id_tipo_peca) {
        this.id_tipo_peca = id_tipo_peca;
    }

    @Column(name = "nome")
    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    @Column(name = "descricao")
    public String getDescricao() {
        return descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

}
